services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: gofullcycle
    ports:
      - 8000:8000
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
